a71: Switch to AIDL NFC2 service
* The HIDL version is outdated for 15 QPR2.
* Fixes:
hardware/nxp/nfc/pn8x/1.2/NxpNfcService.cpp:25:10: fatal error: 'NxpNfc.h' file not found
25 | #include "NxpNfc.h"

Change-Id: I0443c222494af35bb84ab588f48e942aa2a3694e