a71: Kang NFC blobs from m33x
* Pull blobs from 14 UP1A.231005.007 M336BXXSBEYB3 release-keys.
* Fixes:
error: build/soong/fsgen/Android.bp:31:1: module "lineage_a71_generated_vendor_image" variant "android_common" (created by module "soong_filesystem_creator" variant
 "android_common"): packaging conflict at lib64/nfc_nci_nxp.so

Change-Id: I110c88f6df47300f74fc4d22832d509e36406eab