a71: Create camera firmware symlink
* It does not affect on camera as it works without issues.
* Fixes build errors related to copying .bin files on 15 QPR2:
error: build/soong/fsgen/Android.bp:31:1: module "lineage_a71_generated_vendor_image" variant "android_common" (created by module "soong_filesystem_creator" variant "andro
id_common"): packaging conflict at lib64/camera/com.samsung.tuned.lsi_s5kgw1s.bin

Change-Id: I79ea0c6214bb462d0949b44b15020e5db3cbec5d