a71: Do not manually set namespace_imports
* Test: . build/envsetup.sh && breakfast a71 then check PRODUCT_SOONG_NAMESPACES and see "vendor/samsung/a71-common" is configured automatically.
* Fixes:
error: vendor/samsung/a71/Android.bp:1563:1: "libmmcamera_cac3" depends on undefined module "libqdMetaData".
Module "libmmcamera_cac3" is defined in namespace "vendor/samsung/a71" which can read these 3 namespaces: ["vendor/samsung/a71" "vendor/samsung/a7
1-common" "."]

Change-Id: I8e9d90634772a8e4fbed57e9954d3d7589198dc2